package Entities;
// Generated Jan 17, 2017 11:52:41 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Taikhoanadmin generated by hbm2java
 */
@Entity
@Table(name = "taikhoanadmin", catalog = "qlbantuisach")
public class Taikhoanadmin implements java.io.Serializable {

	private Integer maTaiKhoan;

	private String tenTaiKhoan;

	private String matKhau;

	private String diaChi;

	private String sdt;

	public Taikhoanadmin() {
	}

	public Taikhoanadmin(String tenTaiKhoan, String matKhau, String diaChi, String sdt) {
		this.tenTaiKhoan = tenTaiKhoan;
		this.matKhau = matKhau;
		this.diaChi = diaChi;
		this.sdt = sdt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MaTaiKhoan", unique = true, nullable = false)
	public Integer getMaTaiKhoan() {
		return this.maTaiKhoan;
	}

	public void setMaTaiKhoan(Integer maTaiKhoan) {
		this.maTaiKhoan = maTaiKhoan;
	}

	@Column(name = "TenTaiKhoan", nullable = false, length = 25)
	public String getTenTaiKhoan() {
		return this.tenTaiKhoan;
	}

	public void setTenTaiKhoan(String tenTaiKhoan) {
		this.tenTaiKhoan = tenTaiKhoan;
	}

	@Column(name = "MatKhau", nullable = false, length = 25)
	public String getMatKhau() {
		return this.matKhau;
	}

	public void setMatKhau(String matKhau) {
		this.matKhau = matKhau;
	}

	@Column(name = "DiaChi", nullable = false, length = 250)
	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	@Column(name = "SDT", nullable = false, length = 25)
	public String getSdt() {
		return this.sdt;
	}

	public void setSdt(String sdt) {
		this.sdt = sdt;
	}

}
